AWSTemplateFormatVersion: 2010-09-09
Description: Using intrinsic Funstions and parameters
Parameters:
  s3NamePrefix:
    Description: Enter the unique prefix to the name of the S3 bucket to be created
    Type: String
    Default: mybucket
Resources:
  s3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName:
        !Join [
          "-",
          [!Ref s3NamePrefix, !Ref "AWS::StackName", !Ref "AWS::Region"],
        ]
